services:
  postgres:
    image: postgres:16
    container_name: eyetap-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: eyetap
      POSTGRES_USER: eyetap
      POSTGRES_PASSWORD: eyetap
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eyetap"]
      interval: 5s
      timeout: 5s
      retries: 5
    # networks:
    #   - eyetap-main

  backend:
    image: eyetap/backend
    container_name: eyetap-backend
    build:
      context: backend
      dockerfile: ../backend.Dockerfile
    ports:
      - "8080:8080"
    # networks:
    #   - eyetap-main
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eyetap

volumes:
  postgres_data:
  pgadmin_data:

# networks:
#   eyetap-main:
#     driver: bridge
