services:
  postgres:
    image: postgres:16
    container_name: eyetap-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: eyetap
      POSTGRES_USER: eyetap
      POSTGRES_PASSWORD: eyetap
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eyetap"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    image: ghcr.io/eye-tap/backend
    depends_on:
      - postgres
    container_name: eyetap-backend
    build:
      context: backend
      dockerfile: ../backend.Dockerfile
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://127.0.0.1:8080/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/eyetap
      SPRING_DATASOURCE_USERNAME: eyetap
      SPRING_DATASOURCE_PASSWORD: eyetap

  frontend:
    image: ghcr.io/eye-tap/frontend
    depends_on:
      - postgres
    container_name: eyetap-frontend
    ports:
      - "8081:3000"
    healthcheck:
      test: [ "CMD", "curl", "-sf", "http://127.0.0.1:3000" ]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
  pgadmin_data:

# networks:
#   eyetap-main:
#     driver: bridge
